from google.cloud import bigquery

# Types du df
paybox_dtypes = {
    'RemittancePaybox' : 'string',
    'Bank' : 'string' ,
    'Site' : 'string',
    'Rank' : 'string',
    'ShopName' : 'string',
    'IdPaybox' : 'string',
    'Date' : 'string',
    'TransactionId' : 'string',
    'IdAppel' : 'string',
    'DateOfIssue' : 'string',
    'HourOfIssue' : 'string',
    'DateOfExpiry' : 'string', 
    'Reference' : 'string', 
    'EmailCustomer' : 'string', 
    'Type' : 'string', 
    'Canal' : 'string',
    'NumberOfAuthorization' : 'string',
    'Amount' : 'float64',
    'Currency' : 'string',
    'Entity' : 'string',
    'Operator' : 'string',
    'Country' : 'string',
    'CountryIP' : 'string',
    'CardType' : 'string',
    'ThreeDSecureStatus' : 'string',
    'ThreeDSecureInscription' : 'string',
    'ThreeDSecureWarranted' : 'string',
    'RefArchive' : 'string'
}

# Schéma de la table BQ
schema = [
    bigquery.SchemaField("RemittancePaybox", "STRING"),
    bigquery.SchemaField("Bank", "STRING"),
    bigquery.SchemaField("Site", "STRING"),
    bigquery.SchemaField("Rank", "STRING"),
    bigquery.SchemaField("ShopName", "STRING"),
    bigquery.SchemaField("IdPaybox", "STRING"),
    bigquery.SchemaField("Date", "DATE"),
    bigquery.SchemaField("TransactionId", "STRING"),
    bigquery.SchemaField("IdAppel", "STRING"),
    bigquery.SchemaField("DateOfIssue", "DATE"),
    bigquery.SchemaField("HourOfIssue", "STRING"),
    bigquery.SchemaField("DateOfExpiry", "DATE"),
    bigquery.SchemaField("Reference", "STRING"),
    bigquery.SchemaField("EmailCustomer", "STRING"),
    bigquery.SchemaField("Type", "STRING"),
    bigquery.SchemaField("Canal", "STRING"),
    bigquery.SchemaField("NumberOfAuthorization", "STRING"),
    bigquery.SchemaField("Amount", "FLOAT"),
    bigquery.SchemaField("Currency", "STRING"),
    bigquery.SchemaField("Entity", "STRING"),
    bigquery.SchemaField("Operator", "STRING"),
    bigquery.SchemaField("Country", "STRING"),
    bigquery.SchemaField("CountryIP", "STRING"),
    bigquery.SchemaField("CardType", "STRING"),
    bigquery.SchemaField("ThreeDSecureStatus", "STRING"),
    bigquery.SchemaField("ThreeDSecureInscription", "STRING"),
    bigquery.SchemaField("ThreeDSecureWarranted", "STRING"),
    bigquery.SchemaField("RefArchive", "STRING")
]